stages:
  - build
  - test

variables:
  GIT_DEPTH: "3"
  IMAGE_LABELS: >
    --label vcs-url=$CI_PROJECT_URL
    --label com.skypicker.gitlab.ci.builder=$GITLAB_USER_EMAIL
    --label com.skypicker.gitlab.ci.pipeline=$CI_PROJECT_URL/pipelines/$CI_PIPELINE_ID
    --label com.skypicker.gitlab.ci.ref=$CI_BUILD_REF_NAME
    --label com.skypicker.gitlab.ci.build=$CI_PROJECT_URL/builds/$CI_BUILD_ID

image: docker:18.06

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY || true

include:
  - 'https://ci-files.skypicker.com/templates/build/black.yml'

test:pytest:
  image: python:3.6
  before_script:
    - pip install -r requirements-test.txt
  script:
    - pytest test

